import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Skill Up",
  description: "Generated by Skill Up",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex h-[100vh]">
      <div className="hidden md:block  w-[30%] bg-[#1C3268]">
        <div className="font-bold text-2xl text-white flex gap-2 md:gap-4 items-center justify-center pl-2 pt-4 md:p-8">
          <Image
            src={"/images/skillup-icon.png"}
            width={48}
            height={48}
            alt="logo"
          />
          <p>Skill-Up</p>
        </div>
      </div>
      <div className="flex h-[100vh] justify-center items-center  w-full">
        {children}
      </div>
    </main>
  );
}
