---
- hosts: deploy-server
  #become : true
  #become_user: ansadmin
  tasks: 
    - name: Change directory to remote server path
      shell: cd /home/ubuntu/demo
    - name: debug with list
      shell: ls
    - name: debug with whoami
      shell: whoami
    - name: Extract tar file
      shell: tar -xzf app.tar.gz
    - name: Run npm install for dependencies installation
      shell: /home/ubuntu/.nvm/versions/node/v22.6.0/bin/npm install
    - name: pm2 start
      shell: pm2 start npm --name "skillup-webportal-dev" -- run dev
