- hosts: deploy-server
  tasks:
    - name: Run commands in a shell session
      shell: |
        bash -c ' \
        source /home/ubuntu/.nvm/nvm.sh; \
        nvm use 22.6.0; \
        cd /home/ubuntu/demo; \
        tar -xzf app.tar.gz; \
        npm install; \
        pm2 start npm --name "skillup-webportal-dev" -- run dev; \
        pm2 save; \
        pm2 list; \
        '
      register: command_output

    - name: Show output of the commands
      debug:
        msg: "{{ command_output.stdout_lines }}"
