import type { Metadata } from "next";
import DashboardLayout from "../../components/dashbaord/dashboardLayout/DashboardLayout";

export const metadata: Metadata = {
  title: "Skill Up",
  description: "Generated by Skill Up",
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <DashboardLayout>{children}</DashboardLayout>;
}

export default RootLayout;
